# Temporary GitPage Host setup
title: CS230 Deep Learning
baseurl: "/cs230-2019-fall"
repository: "haossr/cs230-2019-fall"

# Theme settings
doks:
    color_theme: blue 
    header:
        logo:
            text: CS230
            image: true
        nav:
            - item_name: Syllabus
              item_url: '/syllabus'
            - item_name: Office Hours
              item_url: '/officehours'
            - item_name: Project
              item_url: '/project'
            - item_name: Section
              item_url: '/section'
            - item_name: Lecture
              item_url: '/lecture'
            - item_name: Blog
              item_url: '/blog'
            - item_name: FAQ
              item_url: '/faq'
    footer:
        content:
            logo:
                text: 
                image:
            copyright: Copyright &copy; 2019. - Stanford University <br>All rights reserved.
        social_list:
            # - network_name: facebook
            #   profile_url: '#'
            # - network_name: twitter
            #   profile_url: '#'
    google_analytics: UA-124237072-3
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
plugins_dir: ./_plugins
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md', 'scripts']
permalink: /:title/

# Course logistics
course:
    quarter: 2019 Fall
    time: Tue 9:00 AM - 10:20 AM
    venue: NVIDIA Auditorium
    piazza: &pz 'https://piazza.com/class/k0rhx3vr6my26c'
    queuestatus:
        url: &qs 'https://queuestatus.com/queues/515'
        name: 'CS230 (2019 Fall)'
    canvas: ''
    midterm_time: 11/06 Wednesday 6-9 PM
    project_timeline:
        proposal: 2019-10-10T23:59:00-07:00
        milestone: 2019-11-05T23:59:00-08:00
        poster_and_report: 2019-12-08T23:59:00-08:00
        poster_session: 12/11 Wednesday 7:30AM - 12:30 PM
        long_date_format: "%B %-d, %A %I:%M %p"
        syllabus_date_format: "%m/%d %A %I:%M %p"
    links:
        syllabus:
            icon: 
            content: Syllabus
            url: '/syllabus'
            external_url: false
        past-projects:
            icon:
            content: Past Projects
            url: '/past-projects'
            external_url: false
        project-sponsoring:
            content: Sponsoring a Project
            url: 'https://docs.google.com/forms/d/e/1FAIpQLSfJOXvQq46sfie8Z6e8Tp8v0_3khker3wrJJR44VyTINcGLiA/viewform'
            external_url: true
        project-2018-win:
            icon:
            content: Winter 2018
            url: '/past-projects/#winter-2018'
            external_url: false
        project-2018-spr:
            icon:
            content: Spring 2018
            url: '/past-projects/#spring-2018'
            external_url: false
        project-2018-fall:
            icon:
            content: Fall 2018
            url: '/past-projects/#fall-2018'
            external_url: false
        project-2019-win:
            icon:
            content: Winter 2019
            url: '/past-projects/#winter-2019'
            external_url: false
        project-2019-spr:
            icon:
            content: Spring 2019
            url: '/past-projects/#spring-2019'
            external_url: false
        video2018:
            icon: 
            content: Lecture videos (Fall 2018)
            url: '/lecture/'
            external_url: false 
        piazza:
            icon: 
            content: Piazza
            url: *pz
            external_url: true
        video:
            icon:
            content: Lecture videos (Canvas)
            url: 'https://canvas.stanford.edu/courses/100571/external_tools/3367'
            external_url: true
        queuestatus:
            icon:
            content: QueueStatus
            url: *qs
            external_url: true
        project_appt_calendly:
            content: Meet with Project TA
            url: '/officehours/#table'
            external_url: true
    staff:
        - name: Andrew Ng
          type: Instructor
          url: https://www.andrewng.org/
          image: andrew.jpg 
        - name: Kian Katanforoosh
          type: Instructor
          url: https://www.linkedin.com/in/kiankatan/
          image: kian.jpg
        - name: Swati Dube 
          type: Coordinator 
          url: http://www.linkedin.com/in/swatidube/
          image: swati.jpg
        - name: Younes Mourri
          type: Course Advisor
          url: https://www.linkedin.com/in/younes-bensouda-mourri-8749b9a9/
          image: younes.jpg
        - name: Hao Sheng
          type: Head TA
          url: https://www.hsheng.org/
          image: hao.png
          zoom_id: 7600992637
          calendly: https://calendly.com/cs230-2019-fall/hao
          OH1: "4:00 pm - 7:00 pm Monday"
    ta:
        - name: Conner Smith
          type: On-campus TA
          url: https://www.linkedin.com/in/conner-smith-220042158/ 
          image: conner.jpeg
          zoom_id: 7844912006
          calendly: https://calendly.com/cs230-2019-fall/conner
          OH1: "6:00 pm - 9:00 pm Thursday"
        - name: Jonathan Braatz
          type: On-campus TA
          url: 
          image: jon.jpg
          zoom_id: 5026279572
          calendly: https://calendly.com/cs230-2019-fall/jon
          OH1: "9:00 am - 12:00 pm Friday"
          OH2: "12:00 pm - 1:00 pm Friday"
        - name: Jo Chuang
          type: On-campus TA
          url: http://linkedin.com/in/jochuang
          image: jo.jpg
          zoom_id: 8543765436
          calendly: https://calendly.com/cs230-2019-fall/jo
          OH1: "3:00 pm - 6:00 pm Tuesday"
        - name: Mohamed El-Geish
          type: External TA
          url: https://elgeish.com
          image: mohamed.jpg
          zoom_id: 8939992795
          calendly: https://calendly.com/cs230-2019-fall/mohamed
          OH1: "11:00 am - 2:00 pm Saturday"
        - name: Sarah Ciresi
          type: On-campus TA
          url: https://www.linkedin.com/in/sarahciresi
          image: sarah.jpg
          zoom_id: 2532092111
          calendly: https://calendly.com/cs230-2019-fall/sarah
          OH1: "1:30 pm - 4:30 pm Thursday"
        - name: Vineet Kosaraju
          type: On-campus TA
          url: http://vineetkosaraju.com
          image: vineet.png
          zoom_id: 2698484179
          calendly: https://calendly.com/cs230-2019-fall/vineet
          OH1: "1:30 pm - 4:30 pm Wednesday"
          OH2: "4:00 pm - 5:00 pm Monday"
        - name: Zahra Koochak
          type: External TA
          url: https://www.linkedin.com/in/zahra-koochak-8bb175a1
          image: zahra.jpg
          zoom_id: 5813391849
          calendly: https://calendly.com/cs230-2019-fall/zahra
          OH1: "7:00 am - 10:00 am Sunday"
        - name: Shahab Mousavi
          type: On-campus TA
          url: https://www.linkedin.com/in/shahab-mousavi-39394738/
          image: shahab.jpg
          zoom_id: 9392472642
          calendly: https://calendly.com/cs230-2019-fall/shahab
          OH1: "3:00 pm - 6:00 pm Saturday"
          OH2: "6:00 pm - 7:00 pm Friday"
        - name: Advay Pal
          type: On-campus TA
          url: http://advaypal.com/
          image: advay.jpg
          zoom_id: 5123418143
          calendly: https://calendly.com/cs230-2019-fall/advay
          OH1: "1:00 pm - 4:00 pm Friday"
          OH2: "12:00 pm - 1:00 pm Thursday"
        - name: Huizi Mao
          type: On-campus TA
          url:
          image: huizi.jpg
          zoom_id: 3119546884
          calendly: https://calendly.com/cs230-2019-fall/huizi
          OH1: "1:00 pm - 4:00 pm Monday"


